[toddler-game]
exten => s,1,Answer()
same => n,Playback(silence/1)
same => n(loop),WaitExten(15)

; Main number pad handler (DTMF audio inputs mid-call)
exten => _[0-9*#],1,Playback(toddler/${EXTEN})
same => n,Goto(s,loop)

; Side and context key handler (Speed dials 701-714)
exten => _7XX,1,Answer()
same => n,Playback(toddler/${EXTEN})
same => n,Hangup()

exten => t,1,Hangup()
exten => i,1,Goto(s,loop)
